### ISSUE TITLE
Password for rooms is a "Text not null" field 

### ISSUE THREAD

**Issue by TheoGermain** [thomasbouix/QuickChat#4]
Rooms can be public or private, so if it is public the password has to be NULL, in the QuickChat_bdd.py file, the field can't be TEXT NOT NULL.

**Comment by diegopanepo** [comment]
The `password` field has to be `TEXT NOT NULL` in case the room is private: we can't give the possibility of creating a private room without password. For the case of a public room, we can simply leave this field in blank, and when accessing the room this field will not be taken into account.

**Comment by diegopanepo** [comment]
I have tested the code by leaving the `password` field in blank and it worked.
